name: Code Scanning with Email Notification

on:
  push:
    branches:
      - main # Runs on push to the main branch

jobs:
  code-scanning:
    name: Code Scanning and Email
    runs-on: ubuntu-latest

    steps:
      # Checkout repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Run CodeQL Analysis (example with CodeQL scanning)
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      # Send email notification with scan results
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.example.com # Replace with your SMTP server (e.g., smtp.gmail.com)
          server_port: 587                # SMTP port (e.g., 587 for TLS)
          username: ${{ secrets.EMAIL_USERNAME }} # Add your email username to repository secrets
          password: ${{ secrets.EMAIL_PASSWORD }} # Add your email password or app-specific password to secrets
          subject: "Code Scanning Results for ${{ github.repository }}"
          body: |
            Code scanning has completed for repository: ${{ github.repository }}
            Commit: ${{ github.sha }}
            View detailed results: ${{ github.server_url }}/${{ github.repository }}/security/code-scanning
          to: "joannamyla@gmail.com"
          from: "joannamyla@gmail.com"

